### ISSUE TITLE
ES6: Use Destructuring Assignment to Assign Variables from Objects

### ISSUE THREAD

**Issue by nathanhannig** [freeCodeCamp/curriculum#213]
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-to-assign-variables-from-objects

Decription
`Use destructuring to obtain the length of the input string str, and assign the length to len in line.`

I believe 'in line' should be a single word: 'inline'

**Comment by joshalling** [comment]
While I agree that the instructions are confusing, I feel like it is also good to at least try to apply a concept like this to a more specific situation. 

Maybe rather than change the challenge we could add a hint to the guide. That way the camper is still being pushed to figure it out on their own.

Thoughts?

**Comment by johnkennedy9147** [comment]
I think this is a poorly written challenge. It is confusing as it relies on campers having an understanding of the difference between string primitives and string objects and how JavaScript automatically converts primitives to objects in order to apply methods or lookup properties.

Given we don't seem to cover these facets of strings in the curriculum prior to this challenge it is unfair to expect them to figure this out in a challenge that is supposed to be about learning destructuring objects.

I think we should change the challenge to explicitly use an object.

**Comment by joshalling** [comment]
@johnkennedy9147 In that case, we would need to update the the tests and contents of this challenge. Could we do something similar the next challenge that uses a nested object? For example:

```javascript
const AVG_TEMPERATURES = {
  today: 77.5,
  tomorrow: 79
};

function getTempOfTmrw(avgTemperatures) {
  "use strict";
  // change code below this line
  const tempOfTomorrow = undefined; // change this line
  // change code above this line
  return tempOfTomorrow;
}

console.log(getTempOfTmrw(AVG_TEMPERATURES)); // should be 79
```
